# KSA / MISA sources (generated skeleton)
# Fill "title", "url", "version", and "scope" later; keep "file" and "sha256" as-is.
sources:
  - id: misa-companies-law
    authority: MISA
    title: "TODO – nice human title for companies-law.pdf"
    file: "companies-law.pdf"
    url: "TODO – official URL if available"
    language: "EN"   # or AR
    version: "TODO – as shown in PDF"
    last_checked: "2025-11-07"
    scope: ["licensing"]   # e.g., licensing, RHQ, companies-law
    citation_granularity: ["section","paragraph"]
    sha256: "aca76e71111e2b8f0c3237ef8f5b678999c63f02de63f82dec18f2b33b3f5ff7"
  - id: misa-e-invoicing-detailed-guideline
    authority: MISA
    title: "TODO – nice human title for e-invoicing_detailed__guideline.pdf"
    file: "e-invoicing_detailed__guideline.pdf"
    url: "TODO – official URL if available"
    language: "EN"   # or AR
    version: "TODO – as shown in PDF"
    last_checked: "2025-11-07"
    scope: ["licensing"]   # e.g., licensing, RHQ, companies-law
    citation_granularity: ["section","paragraph"]
    sha256: "55b7dfb481b8732078ee8fa6264a42a7293ac555b0682a8458a75f634e4ff2e4"
  - id: misa-executive-summary-of-updated-investment-law-en-1
    authority: MISA
    title: "TODO – nice human title for executive-summary-of-updated-investment-law-en-1.pdf"
    file: "executive-summary-of-updated-investment-law-en-1.pdf"
    url: "TODO – official URL if available"
    language: "EN"   # or AR
    version: "TODO – as shown in PDF"
    last_checked: "2025-11-07"
    scope: ["licensing"]   # e.g., licensing, RHQ, companies-law
    citation_granularity: ["section","paragraph"]
    sha256: "292e585735ce3375c092b3b3dfde9edd6bc98d71ad88dff16c4459654d8b3397"
  - id: misa-foreign-investment-law-1
    authority: MISA
    title: "TODO – nice human title for foreign-investment-law-1.pdf"
    file: "foreign-investment-law-1.pdf"
    url: "TODO – official URL if available"
    language: "EN"   # or AR
    version: "TODO – as shown in PDF"
    last_checked: "2025-11-07"
    scope: ["licensing"]   # e.g., licensing, RHQ, companies-law
    citation_granularity: ["section","paragraph"]
    sha256: "3aac52ba071a9f6c7afa7f96f4fbc311c2720f6239c749103587b9e20dd665f3"
  - id: misa-government-tenders-and-procurement-law
    authority: MISA
    title: "TODO – nice human title for government_tenders_and_procurement_law.pdf"
    file: "government_tenders_and_procurement_law.pdf"
    url: "TODO – official URL if available"
    language: "EN"   # or AR
    version: "TODO – as shown in PDF"
    last_checked: "2025-11-07"
    scope: ["licensing"]   # e.g., licensing, RHQ, companies-law
    citation_granularity: ["section","paragraph"]
    sha256: "903c14b7a4090f5597f09249d2e377eac74ee98b38bce4177a275b5432d743d1"
  - id: misa-income-tax-law
    authority: MISA
    title: "TODO – nice human title for income-tax-law.pdf"
    file: "income-tax-law.pdf"
    url: "TODO – official URL if available"
    language: "EN"   # or AR
    version: "TODO – as shown in PDF"
    last_checked: "2025-11-07"
    scope: ["licensing"]   # e.g., licensing, RHQ, companies-law
    citation_granularity: ["section","paragraph"]
    sha256: "a80532cd89e599c34eba9b57863517419e79c74a4d53b82d1bef022edec79b99"
  - id: misa-investment-law-1
    authority: MISA
    title: "TODO – nice human title for investment-law-1.pdf"
    file: "investment-law-1.pdf"
    url: "TODO – official URL if available"
    language: "EN"   # or AR
    version: "TODO – as shown in PDF"
    last_checked: "2025-11-07"
    scope: ["licensing"]   # e.g., licensing, RHQ, companies-law
    citation_granularity: ["section","paragraph"]
    sha256: "bd0456593415a6399eb1aa69afbf5fb459936615a0cbbcb643362588bdd72b0d"
  - id: misa-law-of-value-added-tax
    authority: MISA
    title: "TODO – nice human title for law-of-value-added-tax.pdf"
    file: "law-of-value-added-tax.pdf"
    url: "TODO – official URL if available"
    language: "EN"   # or AR
    version: "TODO – as shown in PDF"
    last_checked: "2025-11-07"
    scope: ["licensing"]   # e.g., licensing, RHQ, companies-law
    citation_granularity: ["section","paragraph"]
    sha256: "acf01622b6f964a1e8ff404a1ae8849c6776f35fa8d96b3240492b00f44f15c0"
  - id: misa-mining-investment-law
    authority: MISA
    title: "TODO – nice human title for mining-investment-law.pdf"
    file: "mining-investment-law.pdf"
    url: "TODO – official URL if available"
    language: "EN"   # or AR
    version: "TODO – as shown in PDF"
    last_checked: "2025-11-07"
    scope: ["licensing"]   # e.g., licensing, RHQ, companies-law
    citation_granularity: ["section","paragraph"]
    sha256: "d2dc93e87196d4330c24e779445ed53302720c705b4ec1eac663034dbc3b3f6a"
  - id: misa-misa-service-manual-12-4-1-edition-english
    authority: MISA
    title: "TODO – nice human title for misa-service-manual-12-4-1-edition-english.pdf"
    file: "misa-service-manual-12-4-1-edition-english.pdf"
    url: "TODO – official URL if available"
    language: "EN"   # or AR
    version: "TODO – as shown in PDF"
    last_checked: "2025-11-07"
    scope: ["licensing"]   # e.g., licensing, RHQ, companies-law
    citation_granularity: ["section","paragraph"]
    sha256: "8a9cea4bab630e6c13f5400ef0f2e56e3c3e2155f1a5c40555268bd140825dbf"
  - id: misa-saudi-investment-law-profile-en-1
    authority: MISA
    title: "TODO – nice human title for saudi-investment-law-profile-en-1.pdf"
    file: "saudi-investment-law-profile-en-1.pdf"
    url: "TODO – official URL if available"
    language: "EN"   # or AR
    version: "TODO – as shown in PDF"
    last_checked: "2025-11-07"
    scope: ["licensing"]   # e.g., licensing, RHQ, companies-law
    citation_granularity: ["section","paragraph"]
    sha256: "209f437c7720037559f52dd34d078336f850e256eb1ed956faff0edbabd63a75"
  - id: misa-social-insurance-law
    authority: MISA
    title: "TODO – nice human title for social-insurance-law.pdf"
    file: "social-insurance-law.pdf"
    url: "TODO – official URL if available"
    language: "EN"   # or AR
    version: "TODO – as shown in PDF"
    last_checked: "2025-11-07"
    scope: ["licensing"]   # e.g., licensing, RHQ, companies-law
    citation_granularity: ["section","paragraph"]
    sha256: "a30f18a3d7c936d80ba61c4f210f0cd38970d6d607c1fdde553be8919420adc8"
  - id: misa-the-investment-law-implementing-regulations-english-1
    authority: MISA
    title: "TODO – nice human title for the-investment-law-implementing-regulations-english-1.pdf"
    file: "the-investment-law-implementing-regulations-english-1.pdf"
    url: "TODO – official URL if available"
    language: "EN"   # or AR
    version: "TODO – as shown in PDF"
    last_checked: "2025-11-07"
    scope: ["licensing"]   # e.g., licensing, RHQ, companies-law
    citation_granularity: ["section","paragraph"]
    sha256: "12e58d2d8da13e83944727f0962279de26d9687a0c0a6b1e67e0e910d13c8cf6"
